<?php
/**
 * Resource List block render template.
 *
 * @package WPCertificationPractice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$posts_to_show = isset( $attributes['postsToShow'] )
	? absint( $attributes['postsToShow'] )
	: 5;

$posts_to_show = max( 1, min( 10, $posts_to_show ) );

$resource_type = isset( $attributes['resourceType'] )
	? sanitize_title( $attributes['resourceType'] )
	: '';

$query_args = array(
	'post_type'      => 'wpcp_resource',
	'post_status'    => 'publish',
	'posts_per_page' => $posts_to_show,
	'no_found_rows'  => true,
);

if ( $resource_type ) {
	$query_args['tax_query'] = array(
		array(
			'taxonomy' => 'wpcp_resource_type',
			'field'    => 'slug',
			'terms'    => $resource_type,
		),
	);
}

$resource_query   = new WP_Query( $query_args );
$resource_list_id = wp_unique_id( 'wpcp-resource-list-' );
?>

<div
	<?php echo get_block_wrapper_attributes(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress Core. ?>
	data-wp-interactive="wpcpResourceList"
	<?php
	echo wp_interactivity_data_wp_context( // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress Core.
		array(
			'isOpen' => true,
		)
	);
	?>
>
<button
	type="button"
	data-wp-on--click="actions.toggle"
	data-wp-bind--aria-expanded="context.isOpen"
	aria-controls="<?php echo esc_attr( $resource_list_id ); ?>"
>
	<span data-wp-bind--hidden="!context.isOpen">
		<?php esc_html_e( 'Hide Resources', 'wp-certification-practice' ); ?>
	</span>

	<span data-wp-bind--hidden="context.isOpen">
		<?php esc_html_e( 'Show Resources', 'wp-certification-practice' ); ?>
	</span>
</button>
<div
	id="<?php echo esc_attr( $resource_list_id ); ?>"
	data-wp-bind--hidden="!context.isOpen"
>
	<?php if ( $resource_query->have_posts() ) : ?>

		<ul>
			<?php
			while ( $resource_query->have_posts() ) :
				$resource_query->the_post();
				?>
				<li>
					<a href="<?php echo esc_url( get_permalink() ); ?>">
						<?php echo esc_html( get_the_title() ); ?>
					</a>
				</li>
			<?php endwhile; ?>
		</ul>

	<?php else : ?>

		<p>
			<?php
			esc_html_e(
				'No Resources are currently available.',
				'wp-certification-practice'
			);
			?>
		</p>

	<?php endif; ?>
	</div>
</div>

<?php wp_reset_postdata(); ?>
